# -*- coding: utf-8 -*-
"""YICLIC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHsoKEYtpDmo_QrECtSRXhLUy-aJANlS

# YICLIC

## import and install packages
"""

# !pip install google-search-results openai
# !pip install chardet
# !pip install transformers torch jieba scipy pandas numpy tqdm
# !pip install fastparquet

# # 升級 safetensors 庫
# !pip install --upgrade safetensors

# # 建議同時升級 transformers 庫，以確保相容性
# !pip install --upgrade transformers

from pathlib import Path
import csv
import re
import os
import chardet
import time
import math
from datetime import datetime, timedelta
import pandas as pd
import numpy as np

from serpapi import GoogleSearch
from openai import OpenAI

# ml
import importlib, lexicon_utils
importlib.reload(lexicon_utils)
from inference_food import predict_food_on_csv

BASE_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = BASE_DIR / "outputs"
REVIEWS_DIR = BASE_DIR / "reviews"

"""## API key 設定方法
### Step 1 — 將 Google Maps(SERPAPI) 與 OpenAI API Key 寫入使用者家目錄下的 .zshrc 設定檔

### Step 2 — 在 .zshrc 中加入以下環境變數設定
> 注意：= 左右不能有空格

```
export SERPAPI_API_KEY="你的 Google Maps Key"
export GPT_API_KEY="你的 OpenAI API Key"
```

### Step 3 — 儲存後重新載入設定檔
```
source ~/.zshrc
```

### 可選：確認已成功載入變數

```
echo $SERPAPI_API_KEY
echo $GPT_API_KEY
```
"""

# API KEY SETTING
try:
    SERPAPI_API_KEY = os.getenv("SERPAPI_API_KEY")
    GPT_API_KEY = os.getenv("GPT_API_KEY")
    print(repr(os.getenv("SERPAPI_API_KEY")))
    # print(repr(os.getenv("GPT_API_KEY")))

    client = OpenAI(api_key = GPT_API_KEY)
    print("API Key 已正確載入!")
except Exception as err:
    print(err)

"""## Capture the command from the Google API"""

# # 抓 place_id
# params = {
#     "engine": "google_maps",
#     "q": "林記豆漿店",
#     "hl": "zh-TW",
#     "api_key": SERPAPI_API_KEY,
# }
# search = GoogleSearch(params)
# results = search.get_dict()

# print(json.dumps(results, indent=2, ensure_ascii=False))

# Google map prompt 設定
# 設定：目標店家 (使用 place_id)
TARGET_SHOPS = [
    {"name": "林記豆漿店", "place_id": "ChIJZZYstakFbjQRgfM2o6Ibc78"},  # 替換成真實 place_id
    {"name": "天一香肉焿順", "place_id": "ChIJKybdGT5OXTQRKjrGMZ9BeFk"},
]

# 每家店最大抓取評論數量
MAX_REVIEWS_PER_SHOP = 5
# 每家店最多抓取頁數
MAX_PAGES_PER_SHOP = 3

# 工具函式
def contains_chinese(text):
    pattern = re.compile(r'[\u4e00-\u9fff]+')
    return bool(pattern.search(text))

# 抓評論
def fetch_reviews(place_id, api_key, next_page_token=None):
    params = {
        "engine": "google_maps_reviews",
        "place_id": place_id,  # ← 你真正要用的 key
        "api_key": api_key,
        "hl": "zh-TW"
    }

    if next_page_token:
        params["next_page_token"] = next_page_token

    search = GoogleSearch(params)
    results = search.get_dict()
    return results, results.get("reviews", [])

# 處理評論（限制每店評論數量 & 分頁）
def process_all_reviews_limited(api_key, target_shops, max_reviews_per_shop=50, max_pages_per_shop=3):
    all_reviews = []

    for shop in target_shops:
        place_id = shop["place_id"]
        restaurant_name = shop["name"]
        print(f"\n--- 處理: {restaurant_name} (ID: {place_id}) ---")

        next_token = None
        page_count = 0
        reviews_for_shop = 0

        while True:
            results, reviews = fetch_reviews(place_id, api_key, next_token)
            # print("DEBUG results:", results)
            # print("DEBUG reviews:", reviews)
            if not reviews:
                print(f"⚠️ {restaurant_name} 沒有評論")
                break

            for review in reviews:
                if reviews_for_shop >= max_reviews_per_shop:
                    print(f"達到 {restaurant_name} 最大評論數量限制 ({max_reviews_per_shop})")
                    break

                rating = review.get("rating", "")
                date = review.get("date", "")
                snippet = review.get("snippet", "")

                if snippet != "" and contains_chinese(snippet):
                    all_reviews.append({
                        "shop": restaurant_name,
                        "snippet": snippet,
                        "date": date,
                        "rating": rating
                    })
                    reviews_for_shop += 1

            if reviews_for_shop >= max_reviews_per_shop:
                break

            next_token = results.get("serpapi_pagination", {}).get("next_page_token")
            page_count += 1
            if not next_token or page_count >= max_pages_per_shop:
                if page_count >= max_pages_per_shop:
                    print(f"達到 {restaurant_name} 最大頁數限制 ({max_pages_per_shop})")
                break

    return all_reviews

# CSV 儲存（覆寫）
def append_to_csv(data, filename):
    fieldnames = ["shop", "snippet", "date", "rating"]

    # 使用 "w" 覆寫整個文件（原本是 "a"）
    with open(filename, "w", newline="", encoding="utf-8-sig") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        # 覆寫模式一定要重新寫 header
        writer.writeheader()

        for row in data:
            writer.writerow({
                "shop": row.get("shop", ""),
                "snippet": row.get("snippet", ""),
                "date": row.get("date", ""),
                "rating": row.get("rating", "")
            })

def run_pipeline(
    target_shops=None,
    api_key: str | None = None,
    max_reviews_per_shop=MAX_REVIEWS_PER_SHOP,
    max_pages_per_shop=MAX_PAGES_PER_SHOP,
):
    """執行整條流程，回傳所有評論與店家分數排序結果。"""
    target_shops = target_shops or TARGET_SHOPS
    api_key = api_key or SERPAPI_API_KEY

    REVIEWS_DIR.mkdir(exist_ok=True)
    print(f"📂 資料夾 '{REVIEWS_DIR}' 已建立或已存在")

    output_filename = REVIEWS_DIR / "multi_location_reviews_for_labeling.csv"

    collected_data = process_all_reviews_limited(
        api_key,
        target_shops,
        max_reviews_per_shop=max_reviews_per_shop,
        max_pages_per_shop=max_pages_per_shop
    )

    if collected_data:
        append_to_csv(collected_data, output_filename)
        print(f"\n--- 成功！共 {len(collected_data)} 條評論已追加到 {output_filename} ---")
    else:
        print("\n⚠️ 沒有收集到任何有效的評論資料。")

    input_csv = output_filename
    output_csv = BASE_DIR / "multi_location_reviews_with_rank_test_pred.csv"
    filtered_output_csv = BASE_DIR / "multi_location_reviews_with_rank_test_food_only.csv"
    model_dir = OUTPUTS_DIR / "bert_food_lexicon_best"

    # === Step 1: 先把 CSV 丟給 ML 過濾 ===
    df_all, df_food = predict_food_on_csv(
        input_csv=str(input_csv),
        output_csv=str(output_csv),
        filtered_output_csv=str(filtered_output_csv),
        model_dir=str(model_dir),
        out_dir_lexicon=str(OUTPUTS_DIR),
        encoding="utf-8-sig",
        threshold=0.5,
    )

    print(f"ML 過濾後，食物相關評論共 {len(df_food)} 條")

    # === Step 2: 從 df_food["snippet"] 裡面取出清理後的評論 ===
    all_reviews_list = []
    for snippet in df_food["snippet"]:
        clean_snippet = str(snippet).replace("\n", " ").strip()
        all_reviews_list.append(clean_snippet)

    print(f"✅ all_reviews_list 已建立，共 {len(all_reviews_list)} 條評論")

    # === Step 3: 轉成你原本使用的格式（編號 + join） ===
    all_reviews_content = "\n\n".join(
        [f"{i+1}. {r}" for i, r in enumerate(all_reviews_list)]
    )

    # 測試印出前 1000 字
    print(all_reviews_content[:1000])

    """## GPT API - Output the manual review rank"""

    scoring_criteria = """你是一個評論標註員
    任務：根據評論內容，標記食物評分(1~5 分，可含 0.5)
    要則：
    只評食物(不考慮價格、環境、服務)
    若評論有「打卡曬贈品、折扣、送小菜」等，評分 -0.5
    評分基準：
    1：極難吃
    2：難吃
    3：普通
    4：好吃
    5：非常好吃
    輸入格式：每個評論間隔兩個換行，沒有遇到兩個換行前為同一個評論
    輸出格式：
    只輸出分數(如：3.5)
    """

    # ====== 組 Prompt ======
    train_prompt = (
        scoring_criteria
        + "\n------------------------------------------\n"
        + "現在請依照以上規則，幫我為底下的餐廳評論打分（0~5分）：\n"
        + all_reviews_content
    )

    print("=== train_prompt 前 1000 字 ===")
    print(train_prompt[:1000])
    print("\n=============================\n")

    # ====== 呼叫 GPT 做評分 ======
    all_scores = []

    for attempt in range(5):
        try:
            print(">> call gpt, reviews:", len(all_reviews_list))
            conversation = client.chat.completions.create(
                # model="gpt-5-mini",
                model="gpt-5-nano",
                messages=[
                    {"role": "system",
                     "content": "你是一位客觀的美食評論家，只回覆每則評論的分數，每行一個分數，不要多說其他文字。"},
                    {"role": "user", "content": train_prompt}
                ]
            )
            print("<< gpt ok")
            reply = conversation.choices[0].message.content.strip()

            # 一行一個分數
            for line in reply.split("\n"):
                line = line.strip()
                try:
                    score = float(line)
                except:
                    score = ""  # 避免非數字造成崩潰
                all_scores.append(score)

            print("✅ 完成 scoring")
            break

        except Exception as e:
            if "Rate limit" in str(e):
                print(f"⚠️ rate limit，等待重試... ({attempt+1}/5)")
            else:
                raise e

    # ====== Debug：檢查前 10 筆 ======
    print("\n=== 前 10 筆檢查：評論 vs 分數 ===")
    for i in range(min(10, len(all_reviews_list))):
        print("\n---")
        print(f"評論：{all_reviews_list[i]}")
        print(f"GPT 給分：{all_scores[i] if i < len(all_scores) else ''}")

    # ====== 將 GPT 分數寫回原始 CSV ======
    input_file = output_filename
    output_file = REVIEWS_DIR / "multi_location_reviews_labeled.csv"

    # 讀取原始 CSV
    with open(input_file, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # 只保留這些欄位
    fieldnames = ["shop", "snippet", "date", "rating", "manual"]

    # 直接依序寫入 manual（不使用 clean_indices）
    for row, score in zip(rows, all_scores):
        row["manual"] = score

    # 若有剩下的行沒分數，補空字串
    for row in rows:
        if "manual" not in row or row["manual"] == "":
            row["manual"] = ""

    # 寫回 CSV，只保留指定欄位
    with open(output_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows([{k: row.get(k, "") for k in fieldnames} for row in rows])

    print(f"✅ GPT 標註的新評論分數已寫回 {output_file}")

    # console 輸出前 10 筆結果
    num_preview = 10
    print(f"\n🔹 前 {num_preview} 筆標註結果:")
    for row in rows[:num_preview]:
        print({k: row.get(k, "") for k in fieldnames})

    # ====== 以下 Dir(T) 排序計算 ======
    input_file = output_file
    df = pd.read_csv(input_file)

    SHOP_COL = "shop"
    DATE_COL = "date"
    MANUAL_COL = "manual"   # 我們只用 manual 作為星級

    print("✅ 已讀入 CSV，前 5 筆：")

    # =========================
    # Step 1. 日期轉天數
    # =========================
    def parse_relative_date(s: str):
        if pd.isna(s):
            return np.nan
        s = str(s).strip()

        if "：" in s:
            s = s.split("：", 1)[-1].strip()

        for fmt in ("%Y/%m/%d", "%Y-%m-%d", "%Y.%m.%d"):
            try:
                dt = datetime.strptime(s.split()[0], fmt)
                return (datetime.now() - dt).days
            except Exception:
                pass

        if "今天" in s:
            return 0
        if "昨天" in s:
            return 1

        m = re.search(r"(\\d+)\\s*年", s)
        if m:
            return int(m.group(1)) * 365
        m = re.search(r"(\\d+)\\s*個?月", s)
        if m:
            return int(m.group(1)) * 30
        m = re.search(r"(\\d+)\\s*(週|周|星期)", s)
        if m:
            return int(m.group(1)) * 7
        m = re.search(r"(\\d+)\\s*天", s)
        if m:
            return int(m.group(1))
        return np.nan

    df["age_days"] = df[DATE_COL].apply(parse_relative_date)
    median_age = df["age_days"].median()
    if pd.isna(median_age):
        median_age = 0
    df["age_days"] = df["age_days"].fillna(median_age)

    # =========================
    # Step 2. 計算時間權重
    # =========================
    half_life_days = 180.0
    lam = math.log(2) / half_life_days
    df["time_weight"] = np.exp(-lam * df["age_days"])
    df["time_weight"] = df["time_weight"].fillna(1.0)

    # =========================
    # Step 3. 對每間店做 Dir(T) 分數（跳過 manual=-1）
    # =========================
    MAX_STAR = 5
    PRIOR_ALPHA = 1.0

    def dirT_score_for_shop_manual(group: pd.DataFrame):
        group_valid = group[(group[MANUAL_COL] != -1) & (pd.notna(group[MANUAL_COL]))]

        if group_valid.empty:
            return pd.Series({f"p_{j}": np.nan for j in range(1, MAX_STAR+1)} | {"dirT_score": np.nan})

        ratings = group_valid[MANUAL_COL].astype(float).values
        weights = group_valid["time_weight"].values

        counts = np.zeros(MAX_STAR, dtype=float)
        for r, w in zip(ratings, weights):
            r_int = int(r)
            if 1 <= r_int <= MAX_STAR:
                counts[r_int - 1] += w

        alpha = counts + PRIOR_ALPHA
        probs = alpha / alpha.sum()
        stars = np.arange(1, MAX_STAR + 1, dtype=float)
        score = float(np.dot(stars, probs))

        data = {f"p_{j}": probs[j-1] for j in range(1, MAX_STAR+1)}
        data["dirT_score"] = score
        return pd.Series(data)

    shop_scores = df.groupby(SHOP_COL, sort=False).apply(dirT_score_for_shop_manual).reset_index()
    shop_scores_sorted = shop_scores.sort_values("dirT_score", ascending=False)

    output_scores_file = REVIEWS_DIR / "shop_manual_dirT_scores.csv"
    shop_scores_sorted.to_csv(output_scores_file, index=False)
    print("✅ 已輸出 CSV：", output_scores_file)

    shop_scores_sorted_records = shop_scores_sorted.to_dict(orient="records")

    return {
        "all_reviews": collected_data,
        "gpt_scores": all_scores,
        "shop_scores_sorted": shop_scores_sorted,
        "shop_scores_sorted_records": shop_scores_sorted_records,
    }


if __name__ == "__main__":
    run_pipeline()
